

service: serverless-slack-bot  
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: dev 
  environment:
    API_KEY: #API_KEY#
functions:
  hello:
    handler: handler.slack
    events:
      - http:
          method: post
          path: /action 

plugins:
  - serverless-offline
